### PR TITLE
Quick hack to "fix" pushing from a shallow clone

### PR DESCRIPTION
**Pull request by brechtm**
Just something to get your feedback on, @jelmer.

This includes a unit test that triggers #705.

As far as I can tell, the proper way to fix this is to not have `_collect_ancestors` "descend" into the parent commits if the current commit is a shallow commit. However, the list of shallow commits is not available in _ObjectStore_. Can we pass a _Repo_ reference to the _ObjectStore_? Or perhaps you can suggest a better approach?

### CODE REVIEW

**Comment by jelmer** [comment]
Hi Brecht, 

Sorry for the slow reply.

> As far as I can tell, the proper way to fix this is to not have _collect_ancestors "descend" into the parent commits if the current commit is a shallow commit. However, the list of shallow commits is not available in ObjectStore. Can we pass a Repo reference to the ObjectStore? Or perhaps you can suggest a better approach?

Passing a repo reference to Repo into ObjectStore would create a circular reference and break the abstractions, so I'd rather avoid doing that.

Perhaps we can simply pass in the list of shallow ids along with have and want?

**Comment by jelmer** [comment]
Thanks for the unit test - I've at least merged that, but marked it as known failing for the moment.

**Comment by brechtm** [comment]
> Sorry for the slow reply.

No problem. What's three days? And it's not like I'm paying for professional support! 😄 

> Passing a repo reference to Repo into ObjectStore would create a circular reference and break the abstractions, so I'd rather avoid doing that.
> 
> Perhaps we can simply pass in the list of shallow ids along with have and want?

I have implemented this in the updated branch. This did require passing the list of shallow commits along quite a number of function call levels. It would be cleaner if the list of shallow commits was also stored in ObjectStore, but I guess it doesn't belong there.

I'm not fully aware of what exactly is happening in MissingObjectFinder, so I invite you to review that. It seems to be doing the right thing, though.

**Comment by jelmer** [comment]
On Mon, Apr 27, 2020 at 03:15:39AM -0700, Brecht Machiels wrote:
> > Sorry for the slow reply.
> No problem. What's three days? And it's not like I'm paying for professional support! 😄 
Hah, for some reason I thought it was a lot more than that. :-)

> > Passing a repo reference to Repo into ObjectStore would create a circular reference and break the abstractions, so I'd rather avoid doing that.
> > 
> > Perhaps we can simply pass in the list of shallow ids along with have and want?
> 
> I have implemented this in the updated branch. This did require passing the list of shallow commits along quite a number of function call levels. It would be cleaner if the list of shallow commits was also stored in ObjectStore, but I guess it doesn't belong there.
> 
> I'm not fully aware of what exactly is happening in MissingObjectFinder, so I invite you to review that. It seems to be doing the right thing, though.
Thanks! This broadly LGTM.

For backwards compatibility reasons, we probably want to default to an
empty set of shallow commits.

I would think that in the case of send-pack the remote repository
would tell you what shallows it has so that you can avoid sending
those. However, such functionality doesn't exist and https://git-scm.com/docs/shallow says:

* It is unclear how "push into/from a shallow repo" should behave.

I'll see if I can merge this with some additional refactoring to hide
the shallow argument.

Jelmer

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by jelmer** [comment]
Merged with some changes - mostly to avoid making API changes. Rather than move shallow data into the object store, I've added a convenience method on Repo that calls .get_shallow().

**Comment by matdrapeau** [comment]
It looks like pulling from shallow clone is raising the same `keyerror` exception

**Pull request closed without merging**
