### PR TITLE
`urllib3` migration

### PR DESCRIPTION
**Pull request by dandersson**
See issue #586. This is an attempt to fix issues with transferring "large" (O(100 kB)) pack sizes in certain environments.

API changes (i.e. changes to "non-underscored" things):

* `dulwich.client.default_urllib2_opener` has been replaced by `dulwich.client.default_urllib3_manager` with otherwise similar input arguments, returning a `urllib3.PoolManager` or `urllib3.ProxyManager`, depending on whether a proxy configuration is given.
* The `opener` argument to `dulwich.client.HttpGitClient` that took a `urllib2` opener instance has been replaced by a `pool_manager` argument that takes a `urllib3` pool manager instance.

I guess this should warrant a major version bump.

---

Initially tested with `urllib3` version 1.21, but anything later in the 1.x series should work.

I added a `requirements.txt` as a common convention for local setup with a known working version. I pinned `urllib3` to its latest available version at the time.

---

I have only tested in Windows (through MSYS2) for Python 2 and Python 3, so there might be surprises lurking, but I wanted to get the pull request up early for others to review and try. I have not yet tested proxy configurations apart from making unit tests run.

---

I have not implemented certificate verification for `urllib3`, which makes the current code issue a warning when performing HTTPS requests: https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl . From what I can tell it should just be to change the dependency from `urllib3` to `urllib3[secure]` and add parameters when initializing the `PoolManager`/`ProxyManager`. I will take a look at this the coming week.

### CODE REVIEW

**Comment by jelmer** [comment]
Thanks, I'll take a look at this over the next couple of days.

The certificate verification issue needs to be resolved before this can be merged, otherwise that's a major regression.

**Comment by dandersson** [comment]
> The certificate verification issue needs to be resolved before this can be merged, otherwise that's a major regression.

Agreed. It has been implemented now.

For Python versions older than 2.7.9, there is an [extra workaround needed to enable SSL verification due to changes made in the standard library](https://urllib3.readthedocs.io/en/latest/user-guide.html#certificate-verification-in-python-2). In the current commit I include this fix since 2.7 is a supported version for Dulwich, but if you feel that "2.7 support" means supporting the latest patch version of the 2.7 branch, I can remove it.

I believe that the `urllib2` solution does not verify HTTPS requests for versions older than 2.7.9 either for the very same reasons, so it would not be a regression against `master` to remove the fix.

**Comment by dandersson** [comment]
Travis CI segfaults for Python 3.7-dev. It seems to be repeatable, but I am not sure why.

I see that 3.7-dev runs were [recently disabled in `master` due to `gevent`](https://github.com/dulwich/dulwich/commit/fa5d8319465ec19d905be999fe42e40fe18fdb13), but my branch includes that commit and still runs it in some respect.

[From the log](https://travis-ci.org/dulwich/dulwich/jobs/334702267):

    $ python -m coverage run -p --source=dulwich -m unittest dulwich.tests.test_suite
    /home/travis/.travis/job_stages: line 57:  3392 Segmentation fault      (core dumped) python -m coverage run -p --source=dulwich -m unittest dulwich.tests.test_suite

**Comment by dandersson** [comment]
I have tried running against GitHub now as well, and I can successfully push a 256 kB file using Dulwich built from this branch, while the current Dulwich `master` fails as described in #586 (tested on Windows, Python 3).

I have also tried it with a repository that has the `http.proxy` Git configuration option set, and proxy settings were applied correctly.

**Comment by jelmer** [comment]
Great, thanks! I'll try to test and merge this during the next couple of days.

**Pull request merged**
