### PR TITLE
Allow configured email addresses to be pre-quoted as "<...>".

### PR DESCRIPTION
**Pull request by monnerat**
While investigating RabbitVCS issue https://github.com/rabbitvcs/rabbitvcs/issues/121, I tracked the problem  down to dulwich.
This PR is a proposed fix.
Thanks for considering it.

### CODE REVIEW

**Comment by jelmer** [comment]
How do you trigger this situation?

**Comment by monnerat** [comment]
> How do you trigger this situation?

Edit file `~/.gitconfig` and set `email = <> `in `[user]`
Then use the `do_commit` method with author/commiter = None

(I'm currently preparing a style fix to this PR to satisfy travis requirements).

**Comment by monnerat** [comment]
Commit 2a2da56 does not add a new test, but changes an existing one. Unquoted e-mail addresses are checked in other tests anyway. I hope it's ok for you.

**Comment by monnerat** [comment]
Thanks for pulling :-)

**Pull request merged**
