### PR TITLE
Add a new SSHVendor to allow plink use for SSH connections.

### PR DESCRIPTION
**Pull request by atbradley**
The PLinkSSHVendor uses the [command-line tool `plink`](https://www.ssh.com/ssh/putty/putty-manuals/0.68/Chapter7.html) instead of `putty` to make SSH connections.

### CODE REVIEW

**Comment by jelmer** [comment]
Is there any reason why you'd want to use putty rather than plink in a SSHVendor?

**Comment by atbradley** [comment]
Not that I can think of. The PuttySSHVendor was already there; I just adapted it to work with plink.

**Comment by jelmer** [comment]
Adding in @Friz-zy, who implemented the putty SSH Vendor and has more background, to comment. Is there any reason why we'd want to invoke putty rather than plink?

**Comment by Friz-zy** [comment]
Hi guys :)
I'm not keen on windows but as I understand, plink is a console alternative of putty and it's already existed in putty distribution
I don't see a big problem of using it )

**Comment by jelmer** [comment]
On Fri, Mar 30, 2018 at 06:19:29AM -0700, Filipp Frizzy wrote:
> Hi guys :)
> I'm not keen on windows but as I understand, plink is a console alternative of putty and it's already existed in putty distribution
> I don't see a big problem of using it )
Let's switch to plink altogether in that case.

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by atbradley** [comment]
I've submitted pull request #619, which simply replaces `putty` with `plink`.

**Pull request merged**
