### PR TITLE
Add python 3.9

### PR DESCRIPTION
**Pull request by jelmer**
Add python 3.9 support.

### CODE REVIEW

**Comment by efiop** [comment]
Hi :)

I might be missing something obvious, but I see this merged into master, but I don't see this in the master https://github.com/dulwich/dulwich/commits/master . Was there a revert+force-push or something?

**Comment by jelmer** [comment]
On Thu, Oct 29, 2020 at 03:59:29PM -0700, Ruslan Kuprieiev wrote:
> I might be missing something obvious, but I see this merged into master, but I don't see this in the master https://github.com/dulwich/dulwich/commits/master . Was there a revert+force-push or something?

Yeah, I backed it out because of some test failures locally and then
forgot to add it back again.

Merged again now - thanks for the reminder.

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by efiop** [comment]
@jelmer Thank you so much for a quick :zap: reply and fix! :pray: Looking forward to a new release with the 3.9 wheels.

**Comment by jelmer** [comment]
Wheels should be available for Windows and Mac OS X; for Linux, the action that I'm using to build the wheels seems to be failing due to this issue: https://github.com/RalfG/python-wheels-manylinux-build/issues/26

**Comment by efiop** [comment]
@jelmer Tried the fix in the linked PR in that ticket, seems to work great. I'll submit a PR in a sec.

**Comment by efiop** [comment]
@jelmer Created https://github.com/dulwich/dulwich/pull/808 Please take a look when you have time. Thanks! :slightly_smiling_face:

**Pull request merged**
