### PR TITLE
Performance of porcelain status

### PR DESCRIPTION
**Pull request by POD666**
Looks like `porcelain.status()` stuck at my `node_modules`. I took a brief look and looks like the following changes work for me.

You might also want to use it in other places like `clean` and `add`.

### CODE REVIEW

**Comment by jelmer** [comment]
Did you mean to propose this against master? 0.19 is no longer maintained.

**Comment by jelmer** [comment]
Also /cc @pmrowla  as somebody who has touched this code recently.

**Comment by pmrowla** [comment]
@POD666 have you tried the latest master branch? This looks like the same issue which should be fixed in https://github.com/dulwich/dulwich/pull/853

**Comment by POD666** [comment]
@pmrowla, you are right, that PR looks very similar.

I stay on 0.19.* as it seems to support py2.

**Pull request closed without merging**
